# Generated by Django 5.0.6 on 2024-05-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_number', models.IntegerField()),
                ('creation_date', models.DateTimeField()),
                ('name_model', models.CharField(max_length=200)),
                ('name_order', models.CharField(max_length=200)),
                ('name_operation', models.CharField(max_length=200)),
                ('number_operation', models.IntegerField()),
                ('name_work_center_name', models.CharField(max_length=200)),
                ('Full_name_of_the_workers', models.CharField(max_length=200)),
                ('time_of_the_master_call', models.DateTimeField()),
                ('time_of_the_controller_call', models.DateTimeField()),
                ('full_name_of_the_master_who_called', models.CharField(max_length=200)),
                ('full_name_of_the_responding_controller', models.CharField(max_length=200)),
                ('time_of_the_controller_response', models.DateTimeField()),
                ('full_name_of_the_controller_who_made_the_decision', models.CharField(max_length=200)),
                ('time_of_the_controller_decision', models.DateTimeField()),
                ('solution', models.CharField(max_length=200)),
            ],
        ),
    ]
