# Generated by Django 5.0.6 on 2024-05-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_alter_listjobs_solution'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListCompletedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_number', models.IntegerField()),
                ('creation_date', models.DateTimeField()),
                ('name_model', models.CharField(max_length=200)),
                ('name_order', models.CharField(max_length=200)),
                ('name_operation', models.CharField(max_length=200)),
                ('number_operation', models.IntegerField()),
                ('name_work_center_name', models.CharField(max_length=200)),
                ('Full_name_of_the_workers', models.CharField(max_length=200)),
                ('time_of_the_master_call', models.DateTimeField()),
                ('time_of_the_controller_call', models.DateTimeField()),
                ('full_name_of_the_master_who_called', models.CharField(max_length=200)),
                ('full_name_of_the_responding_controller', models.CharField(max_length=200)),
                ('time_of_the_controller_response', models.DateTimeField()),
                ('full_name_of_the_controller_who_made_the_decision', models.CharField(max_length=200, null=True)),
                ('time_of_the_controller_decision', models.DateTimeField()),
                ('solution', models.CharField(choices=[('waiting for the controller', 'waiting for the controller'), ('accepted', 'accepted'), ('not accepted', 'not accepted'), ('defective', 'defective')], max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='listjobs',
            name='full_name_of_the_controller_who_made_the_decision',
        ),
        migrations.RemoveField(
            model_name='listjobs',
            name='full_name_of_the_master_who_called',
        ),
        migrations.RemoveField(
            model_name='listjobs',
            name='full_name_of_the_responding_controller',
        ),
        migrations.RemoveField(
            model_name='listjobs',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='listjobs',
            name='time_of_the_controller_call',
        ),
        migrations.RemoveField(
            model_name='listjobs',
            name='time_of_the_controller_decision',
        ),
        migrations.RemoveField(
            model_name='listjobs',
            name='time_of_the_controller_response',
        ),
        migrations.RemoveField(
            model_name='listjobs',
            name='time_of_the_master_call',
        ),
        migrations.AddField(
            model_name='listjobs',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
