# Generated by Django 5.0.6 on 2024-05-31 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0003_listcompletedjobs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listjobs',
            old_name='Full_name_of_the_workers',
            new_name='full_name_of_the_workers',
        ),
    ]
